######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}

{{- if not .Values.certificates.caPairSecretName }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}-rag-selfsigned-issuer
  labels:
{{ include "rag.common.label" . | indent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-rag-selfsigned-ca
  labels:
{{ include "rag.common.label" . | indent 4 }}
spec:
  isCA: true
  renewBefore: {{  .Values.certificates.renewBefore }} # 15d
  commonName: rag
  secretName: {{ include "rag.ca.secret.name" . }} 
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  issuerRef:
    name: {{ $fullName }}-rag-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end -}}