{{ $fullname := include "agenticbuilder.fullname" . }}
{{- $root := . -}}
{{- $deploymentType := include "agenticbuilder.runner.list" $root | fromJsonArray -}}

apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: {{ $fullname }}-apisix-tls
  annotations:
    kubernetes.io/ingress.class: {{ .Values.common.apisix.ingressClassName }}
spec:
  hosts:
    - {{ $fullname }}-{{ .Values.ams.name }}
    {{- range $deploymentType }}
    {{- $currentDeploymentType := . }}
    - {{ $fullname }}-{{ $root.Values.runner.name }}-{{ $currentDeploymentType }}
    {{- end }}
    - {{ $fullname }}-{{ .Values.credentialManager.name }}
    - {{ .Values.common.apisix.serviceName }}
  {{- range $myList := include "agenticbuilder.microservices.list" . | fromJsonArray }}
    - {{ . }}
  {{- end }}
  {{- $deploymentType := include "agenticbuilder.runner.list" $root | fromJsonArray }}
  {{- range $deploymentType }}
  {{- $currentDeploymentType := . }}
    - runner-{{ $currentDeploymentType }}
  {{- end }}
  
  {{- if .Values.common.apisix.extraTLSHosts }}
    {{- range .Values.common.apisix.extraTLSHosts }}
    - "{{ . }}"
    {{- end }}
  {{- end }}
  secret:
    name:  {{ include "agenticbuilder.cert.name" . }}
    namespace: {{ .Release.Namespace }}