# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullname := include "agenticbuilder.fullname" . }}
{{ $unoFullName := include "uno.fullname" . }}

apiVersion:  v1
kind:  ConfigMap
metadata: 
  name:  "{{ $fullname }}-common-configmap"
data: 
    POSTGRES_USER: {{ tpl .Values.common.postgres.postgresUser . }}
    POSTGRES_DB : {{ tpl .Values.common.postgres.postgresDB . }}
    POSTGRES_PORT: {{ tpl (toString .Values.common.postgres.postgresPort) .  | quote}}

    CREDENTIAL_MANAGER_HOST: {{ tpl (printf "https://%s-%s" (include "agenticbuilder.fullname" .) .Values.credentialManager.name) . | quote }}
    CREDENTIAL_MANAGER_PORT: {{ tpl (toString .Values.credentialManager.port) . | quote }}
    AMS_API_HOST: {{ tpl (printf "https://%s-%s" (include "agenticbuilder.fullname" .) .Values.ams.name) . | quote }}
    AMS_API_PORT: {{ tpl (toString .Values.ams.port) . | quote }}

    TOKEN_PROVIDER: {{ tpl (default "STARLETTE" .Values.common.config.tokenProvider) . }}
    TOKEN_PROVIDER_OIDC_SERVER_URL: {{ tpl .Values.common.config.tokenProviderOIDCServerURL . | quote }}
    TOKEN_PROVIDER_DEFAULT_REALM: {{ tpl (default "uno" .Values.common.config.tokenProviderDefaultRealm) . | quote }}
    TOKEN_PROVIDER_CLIENT_ID: {{ tpl .Values.common.config.tokenProviderClientId . | quote }}
    TOKEN_PROVIDER_CLIENT_SECRET: {{ tpl .Values.common.config.tokenProviderClientSecret . | quote }}
    TOKEN_PROVIDER_OPEN_ID_DISCOVERY: {{ tpl (default "/.well-known/openid-configuration" .Values.common.config.tokenProviderOpenIdDiscovery) . | quote }}
    TOKEN_PROVIDER_OIDC_REALM_KEY: {{ tpl (default "realms/" .Values.common.config.tokenProviderOidcRealmKey) . | quote }}
    
    # It can be a path to a file or the content of the file
    TOKEN_PROVIDER_CERT_PRIVATE_KEY: {{ tpl (default "/jwt/private_key.pem" .Values.common.config.tokenProviderCertPrivateKey) . | quote }}
    TOKEN_PROVIDER_CERT_PUBLIC_KEY: {{ tpl (default "/jwt/public_key.pem" .Values.common.config.tokenProviderCertPublicKey) . | quote }}

    TOKEN_PROVIDER_CERT_ISSUER: {{ tpl .Values.common.config.tokenProviderCertIssuer . | quote }}
    TOKEN_PROVIDER_CERT_EXTRA_CLAIMS: {{ tpl .Values.common.config.tokenProviderCertExtraClaims . | quote }}
    TOKEN_PROVIDER_EXPIRATION_TIME_IN_S: {{ tpl (default "3600" .Values.common.config.tokenProviderExpirationTimeInS) . | quote }}
    TOKEN_PROVIDER_ENV_VAR: {{ tpl (default "HCL_AUTH_TOKEN" .Values.common.config.tokenProviderEnvVar) . | quote }}
    TOKEN_PROVIDER_MOCK_VALUE: {{ tpl .Values.common.config.tokenProviderMockValue . | quote }}

    ENABLE_AUTHENTICATION: {{ tpl (default "true" .Values.common.config.enableAuthentication) . | quote }}
    OIDC_SERVER_URL: {{ tpl .Values.authorization.oidcServerURL . | quote }}
    OIDC_CLIENT_ID: {{ tpl .Values.common.config.OIDCClientId . | quote }}
    KEYCLOAK_REALM: {{ tpl .Values.common.config.keycloakRealm . | quote }}
    #HCL_AUTHORIZATION_HTTPS___WAJWT_API: {{ tpl (default "/opt/certs/jwt/uno-jwt.crt" .Values.common.config.internalGatewayCertPath) . | quote }}
    #HCL_AUTHORIZATION_HTTPS___WAJWT_APIGATEWAY: {{ tpl (default "/opt/certs/jwt/uno-jwt.crt" .Values.common.config.APIKeyCertPath) . | quote }}
    CA_FOLDER_PATH: {{ tpl (default "/ca" .Values.common.config.caFolderPath) . | quote }}
    CA_CERTIFICATE_PATHS: {{ tpl .Values.common.config.caCertificatePaths . | quote }}
    CA_CERTIFICATE: {{ tpl .Values.common.config.caCertificate . | quote }}

    UNO_URL: {{ tpl .Values.common.config.unoURL . | quote }}
    UNO_TOKEN_PROVIDER: {{ tpl (default "STARLETTE" .Values.common.config.unoTokenProvider) . | quote }}
    UNO_TOKEN: {{ tpl .Values.common.config.unoToken . | quote }}