# This secret is used to store cloud services credentials
apiVersion: v1
kind: Secret
{{- $fullname := include "agenticbuilder.fullname" . }}
{{- $secretname := printf "%s-%s-encryption-key" $fullname .Values.credentialManager.name }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace $secretname }}
apiVersion: v1
kind: Secret
metadata: 
  name: "{{ $fullname }}-{{ .Values.credentialManager.name }}-encryption-key"
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- if $previous.data }}
  encryption-key: {{ index $previous.data "encryption-key" }}
  {{ else }}
  encryption-key: {{ randAlphaNum 32 | b64enc | b64enc | quote }}
  {{ end }}