######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apikey-secret
  labels:
{{ include "rag.common.label" . | indent 4 }}
type: "Opaque"
data:
  gcp-vertexai-svc.json: {{ include "rag.apikey" . }}
