######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.serviceName" . }}
  labels:
    app: "{{ .Values.app.name }}"
spec:
  selector:
    app: "{{ .Values.app.name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}