{{- $root := .  -}}
{{- $deploymentType := include "agenticbuilder.runner.list" $root | fromJsonArray -}}
{{- range $deploymentType}}
{{- $currentDeploymentType := . -}}

{{ $fullname :=  include "agenticbuilder.fullname" $root }}
{{ $unoFullName := include "uno.fullname" $root }}
{{- $runnerName := printf "%s-%s-%s" $fullname $root.Values.runner.name $currentDeploymentType | trunc 80 }}

apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: {{ $runnerName }}
  annotations:
    kubernetes.io/ingress.class: {{ $root.Values.common.apisix.ingressClassName }}
spec:
  loadbalancer:
    type: roundrobin
  scheme: https
  ingressClassName: {{ $root.Values.common.apisix.ingressClassName }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: "{{ $runnerName }}-route"
  annotations:
    kubernetes.io/ingress.class: {{ $root.Values.common.apisix.ingressClassName }}
spec:
  ingressClassName: {{ $root.Values.common.apisix.ingressClassName }}
  http:
  - name: "main-route"
    match:
      paths:
      - "/{{ $runnerName }}/*"
      - "/runner-{{ $currentDeploymentType }}/*"
      {{- if eq $currentDeploymentType "prod"}}
      - "/discovery"
      {{- end }}
    backends:
    - serviceName: {{ $runnerName }}
      servicePort: {{ $root.Values.runner.port }}
    websocket: true
    plugins:
    - name : serverless-pre-function
      enable: true
      config:
        phase: "rewrite"
        functions:
          - |
            return function(_,ctx)
              ctx.var.rewrited_uri = ctx.var.uri
              ctx.var.rewrited_uri = string.gsub(ctx.var.rewrited_uri, "/{{ include "agenticbuilder.replace.dash.percentdash" $runnerName }}%-?%d*/", "")
              ctx.var.rewrited_uri = string.gsub(ctx.var.rewrited_uri, "/runner%-{{ $currentDeploymentType }}/", "")
              ctx.var.rewrited_uri = string.gsub(ctx.var.rewrited_uri, "/discovery", "discovery")
            end    
    - name: proxy-rewrite
      enable: true
      config:
        uri: "/$rewrited_uri"

---
{{- end}}