{{- if .Values.runner.hpa.enabled -}}
{{- $root := .  -}}
{{- $deploymentType := include "agenticbuilder.runner.list" $root | fromJsonArray -}}
{{- range $deploymentType}}
{{- $currentDeploymentType := . -}}

{{ $fullname :=  include "agenticbuilder.fullname" $root }}
{{ $unoFullName := include "uno.fullname" $root }}
{{- $runnerName := printf "%s-%s-%s" $fullname $root.Values.runner.name $currentDeploymentType }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $runnerName }}-hpa
  labels:
    {{- include "agenticbuilder.labels" $root | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ $runnerName }}
  minReplicas: {{ default 1 $root.Values.runner.hpa.minReplicas }}
  maxReplicas: {{ default 10 $root.Values.runner.hpa.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: agents_running_per_pod
      target:
        type: Value
        averageValue: {{ sub ($root.Values.runner.config.maxAgents | default 5) 1 }}
---
{{- end}}
{{- end}}
