# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "aipilot.fullName" . }}
{{- $root := . -}}
#####################################################################
#
#####################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-{{ .Values.pilotActions.name }}"
  labels:
    {{- include "aipilot.labels" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount .Values.pilotActions.replicaCount}}
  selector:
    matchLabels:
{{ include "aipilot.selectorLabels.backend" (list $root .Values.pilotActions) | indent 6}}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "aipilot.selectorLabels.backend" (list $root .Values.pilotActions) | nindent 8 }}
    spec:
{{ include "aipilot.pull.secret" . | indent 6 }}
{{ include "aipilot.serviceAccountName" . | indent 6 }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: https-cert
          secret:
            secretName: {{ include "aipilot.cert.name" . }}
        {{- if .Values.translation.google.credentials }}
        - name: google-credentials
          secret: 
            secretName: {{ .Release.Name }}-aipilot-google-credentials
        {{- end }}
      containers:
        - name: "{{ $fullName }}-{{ .Values.pilotActions.name }}"
          {{- include "aipilot.image" (list $root .Values.pilotActions) | nindent 10 -}}
          {{- include "aipilot.imagePullPolicy" (list $root .Values.pilotActions) | nindent 10 -}}          
          {{- include "aipilot.resources" .Values.pilotActions | nindent 10 }}
          command: ["/bin/bash", "-c", "rasa run actions --auto-reload -p {{ default 5055 .Values.pilotActions.port }} --ssl-certificate /var/actions-secret/tls.crt --ssl-keyfile /var/actions-secret/tls.key"]
          ports:
            - containerPort: {{ default 5055 .Values.pilotActions.port }}
              name: port-{{ default 5055 .Values.pilotActions.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ $fullName }}-{{ .Values.pilotActions.name }}-configmap
            - configMapRef:
                name: {{ .Release.Name }}-aipilot-translation-config
          volumeMounts:
            {{- if .Values.translation.google.credentials }}
            - name: google-credentials
              subPath: google-credentials.json
              mountPath: /tmp/google-credentials.json
              readOnly: true
            {{- end }}
            - name: https-cert
              mountPath: "/var/actions-secret"
              readOnly: true
            - name: https-cert
              mountPath: "/opt/app-root/lib/python3.9/site-packages/certifi/cacert.pem"
              subPath: ca.crt
              readOnly: true
            - name: https-cert
              mountPath: "/etc/pki/ca-trust/source/anchors/ca-cert.crt"
              subPath: ca.crt
              readOnly: true
