# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "aipilot.fullName" . }}
{{- $root := . -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-{{ .Values.pilotActions.name }}"
  labels:
{{ include "aipilot.selectorLabels.backend" (list $root .Values.pilotActions) | indent 4}}
spec:
  selector: {{- include "aipilot.selectorLabels.backend" (list $root .Values.pilotActions) | nindent 4}}
  ports:
    - name: port-{{ default 5055 .Values.pilotActions.port }}
      protocol: TCP
      port: {{ default 5055 .Values.pilotActions.port }}
      targetPort: port-{{ default 5055 .Values.pilotActions.port }}
  type: ClusterIP