# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "aipilot.fullName" . }}
apiVersion:  v1
kind:  ConfigMap
metadata: 
  name:  "{{ $fullName }}-{{ .Values.pilotNlg.name }}-configmap"
data:
{{- if .Values.pilotNlg.config }}
{{ toYaml .Values.pilotNlg.config | indent 2 }}
{{ end }}
  CERT_PATH: "/var/ngl-secret/ca.crt"
  CERT_DIR: "/etc/ssl/certs/"
  SSL_CERT_FILE: "/var/ngl-secret/ca.crt"
  SSL_CERT_DIR: "/etc/ssl/certs/"
  REQUESTS_CA_BUNDLE: "/var/nlg-secret/ca.crt"