######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
apiVersion: v2
name: rag-service
description: A Helm chart for RAG service
type: application
version: 0.1.0
appVersion: 0.1.0