######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################

global:
 
app:
  name: "rag-service"  # Application name
  replicas: 1  # Number of replicas
  
# Configuration settings for the application
config:
  #EXAMPLE OF GOOGLE GCP KEY MANDATORY IF CLOUD 
  gcp_key: |-
      {
        "type": "service_account",
        "project_id": "",
        "private_key_id": ""
      }

certificates:
  # Use customized certificate
  useCustomizedCert: false
  # Secret name containing the CA to be used to sign the certificates
  # If left empty, it will create a default CA
  caPairSecretName: 
  # Use a custom issuer
  customIssuer: false
  # Organization name for the certificates
  organization: hcl
  # Duration before the certificates are renewed
  renewBefore: 360h
  # Duration for which the certificates are valid
  duration: 2160h
  # Secret name for the certificate
  certSecretName: "{{ .Release.Name }}-rag-certificate"
  # Issuer name if using a custom issuer
  issuerName:

serviceAccount: ""
additionalPullSecret : ""

# Container configuration
container:
  name: "rag-service-container"  # Container name
  image: "hcl-aipilot-rag-backend" 
  registry: "hclcr.io/slt/uno"  # Image name
  tag: 2.1.0.0  # Image tag
  imagePullPolicy: "Always"  # Image pull policy
  port: 9999  # Container port

vectordb:
  # The name of the service of the pgvector
  name: "pgvector" 

# ConfigMap settings
configMap:
  name: "rag-service-config"  # ConfigMap name


probe:
  tcpSocket:
    port: 9999  # Port for TCP socket probe
  initialDelaySeconds: 60  # Initial delay for probe
  periodSeconds: 10  # Probe period
  timeoutSeconds: 20  # Probe timeout
  successThreshold: 1  # Success threshold
  failureThreshold: 6  # Failure threshold

# Resource limits and requests
resources:
  limits:
    cpu: "1"  # CPU limit
    memory: "2G"  # Memory limit
  requests:
    cpu: "200m"  # CPU request
    memory: "256Mi"  # Memory request
hpa:
  name: "rag-service"  # HPA name
  deploymentName: "rag-service"  # Name of the deployment to scale
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 2  # Maximum number of replicas
  metricName: "cpu"  # Name of the resource to measure
  averageUtilization: 50  # Target average utilization percentage

### Authorization/Authentication settings ###
authorization:
  #EXAMPLE HCL_AUTHORIZATION_HTTPS___PILOT_CORE_5005: <secret-name >
  certs:
    #HCL_AUTHORIZATION_HTTPS___PILOT_CORE_5005: pilot-cert
    #HCL_AUTHORIZATION_HTTPS___WAJWT_API: /opt/certs/jwt/uno-jwt.crt
    #HCL_AUTHORIZATION_HTTPS___WAJWT_APIGATEWAY: /opt/certs/jwt/uno-jwt.crt
    #HCL_AUTHORIZATION_TEST: /opt/certs/jwt/pilot-jwt.crt

  # TO ENABLE OIDC AUTHENTICATION
  #oidcServerURL: "https://hcl-uno-keycloak-ssl:8443"

# Service configuration
service:
  name: "rag-service"  # Service name
  port: 9999  # Service port
  targetPort: 9999  # Target port on the container
  type: "ClusterIP"  # Service type

podSecurityContext: {}