# This secret is used to store cloud services credentials
{{ $secretName := printf "%s-postgres-password-secret" .Release.Name  }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ $secretName }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- if $previous.data }}
  password: {{ index $previous.data "password" }}
  postgres-password: {{ index $previous.data "postgres-password" }}
  replication-password: {{ index $previous.data "replication-password" }}
  {{- else if .Values.global.postgresPassword }}
  password: {{ .Values.global.postgresPassword | b64enc }}
  postgres-password: {{ .Values.global.postgresAdminPassword | b64enc }}
  replication-password: {{ .Values.global.postgresReplicationPassword | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
  postgres-password: {{ randAlphaNum 32 | b64enc }}
  replication-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}