# This secret is used to store cloud services credentials
apiVersion: v1
kind: Secret
  {{ $secretname := printf "%s-%s" .Release.Name  "cloud-credentials" }}
  {{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretname }}
metadata:
  name: {{ $secretname }}
  labels:
{{- if $previous }}
    update-secret: "true"
{{ end }}
{{ include "uno.common.label" . | indent 4 }}
type: "Opaque"
data:
{{- if and .Values.config.genai.enabled .Values.config.genai.internal .Values.global.cloudCredentials.gcp.serviceFile }}
  gcp-vertexai-svc.json: {{ .Values.global.cloudCredentials.gcp.serviceFile | quote }}
{{- end }}
{{- if and .Values.config.genai.enabled .Values.config.genai.internal .Values.global.cloudCredentials.aws.secretAccessKey }}
  AWS_SECRET_KEY: {{ .Values.global.cloudCredentials.aws.secretAccessKey | b64enc | quote }}
{{- end }}
{{- if and .Values.config.genai.enabled .Values.config.genai.internal .Values.global.cloudCredentials.azure.apiKey }}
  AZURE_AI_SERVICE_APIKEY: {{ .Values.global.cloudCredentials.azure.apiKey | b64enc | quote }}
{{- end }}
{{- if and .Values.config.genai.enabled .Values.config.genai.internal .Values.global.cloudCredentials.openai.apiKey }}
  OPEN_AI_SERVICE_APIKEY: {{ .Values.global.cloudCredentials.openai.apiKey | b64enc | quote }}
{{- end }}