####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if .Values.global.extraImages }}
{{ $fullName := include "fullname" . }}
{{- $extraImageList := include "uno.extraImages" . | fromJsonArray -}}
{{- $root := . -}}
{{- range $index, $extraImage := $extraImageList -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-extra-{{ $index }}
  labels:
    app: {{ $fullName }}-extra-{{ $index }}
{{ include "uno.common.label" $root | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $fullName }}-extra-{{ $index }}
    app.kubernetes.io/instance: {{ $fullName }}-extra-{{ $index }}
---
{{- end -}}
{{- end }}