# This secret is used to store cloud services credentials
apiVersion: v1
kind: Secret
{{ $secretname := printf "%s-%s" .Release.Name  "shared-key" }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
  labels:
    app: {{ $secretname }}
{{ include "uno.common.label" . | indent 4 }}
data:
  {{- if $previous.data }}
  shared-key: {{ index $previous.data "shared-key" }}
  {{ else }}
  shared-key: {{ randAlphaNum 32 | b64enc }}
  {{ end }}