# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
{{ $secretname := printf "%s-%s" .Release.Name  "uno-secret" }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretname }}
metadata:
  name: {{ $secretname }}
  labels:
{{- if $previous }}
    update-secret: "true"
{{ end }}
{{ include "uno.common.label" . | indent 4 }}
type: "Opaque"
data:
  {{- if $previous }}
  KEYSTORE_PASSWORD: {{ $previous.data.KEYSTORE_PASSWORD }}
  {{- else }}
  KEYSTORE_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.database.password |default "" | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.password |default "" | b64enc | quote }}
  {{- if and $previous $previous.data $previous.data.ENCRYPTION_KEY }}
  {{- $storedKeys := $previous.data.ENCRYPTION_KEY | b64dec }}
  {{- $storedKeyList := $storedKeys | splitList "," }}
  {{- $storedKey := index $storedKeyList 0 }}
  {{- if .Values.config.encryption.key }}
  {{- if eq $storedKey .Values.config.encryption.key }}
  ENCRYPTION_KEY: {{ $previous.data.ENCRYPTION_KEY }}
  {{- else }}
  ENCRYPTION_KEY: {{ (printf "%s,%s" .Values.config.encryption.key  $storedKeys) | b64enc | quote  }}
  {{- end }}
  {{- else }}
  ENCRYPTION_KEY: {{ $previous.data.ENCRYPTION_KEY }}
  {{- end }}
  {{- else }}
  ENCRYPTION_KEY: {{ .Values.config.encryption.key |default (randAlphaNum 8) | b64enc | quote }}
  {{- end }}
  OIDC_SECRET: {{ .Values.authentication.oidc.credentialSecret | default "" | b64enc | quote }}
{{- if .Values.config.genai.proxy.password }}
  GENAI_PROXY_PASSWORD: {{ .Values.config.genai.proxy.password | b64enc | quote }}
{{- end }}
{{- if .Values.config.genai.betaKey }}
  GENAI_API_KEY: {{ .Values.config.genai.betaKey | b64enc | quote }}
{{- end }}
{{- if .Values.config.license.proxy.password }}
  LICENSE_PROXY_PASSWORD: {{ .Values.config.license.proxy.password | b64enc | quote }}
{{- end }}
