{
 "title": "UnO Dashboard - %NAMESPACE% - %RELEASE%",
 "tags": [ "hcl-uno" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "%NAMESPACE%" },
   { "name": "Release", "query": "%RELEASE%" },
   { "name": "cpuDur", "query": "[45s]" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=~\"$Release-.*\", namespace=~\"$Namespace\"}, pod)"
    }
   },
   {
    "name": "tenant_name",
    "query": {
     "query": "label_values(application_uno_tenant_number{namespace=~\"$Namespace\", release=~\"$Release\"},tenant_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# UnO Dashboard\n* Namespace: ${Namespace}\n* Helm Release: ${Release}"
   }
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Jobs by status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "round(\n  sum by(jobstatus) (\n    avg by (tenant_name, jobstatus, jobexternalstatus) (application_uno_orchestrator_jobs_count_jobs{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\", jobstatus=~\".+\"} >= 0)\n  )\n)",
     "legendFormat": "{{jobstatus}}"
    },
    {
     "expr": "round(\n  sum (\n    avg by (tenant_name) (application_uno_orchestrator_inactivejs_count_js{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"} >= 0)\n  )\n)",
     "legendFormat": "NOT_ACTIVE_JS"
    }
   ]
  },
  {
   "title": "Linked Workstations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(\n  sum by(folder) (\n    avg by (tenant_name, folder, name) (\n        application_uno_workstation_linked_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\", folder=~\".+\"} >= 0\n    )\n  )\n)",
     "legendFormat": "{{folder}}"
    },
    {
     "expr": "avg by (deployment) (kube_deployment_status_replicas_available{deployment=~\"$Release-agentmanager\", namespace=~\"$Namespace\"})",
     "legendFormat": "agentmanager replica count"
    }
   ]
  },
  {
   "title": "Execution rate on orchestrator and scheduler",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "jobs/min" } },
   "targets": [
    {
     "expr": "sum (\n  avg by (tenant_name, pod) (\n    rate(application_uno_orchestrator_submission_count_number_total{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval])\n  )\n) * 60",
     "legendFormat": "orchestrator submission rate"
    },
    {
     "expr": "sum (\n  avg by (tenant_name, pod) (\n    rate(application_uno_scheduler_submission_count_number_total{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval])\n  )\n) * 60",
     "legendFormat": "scheduler submission rate"
    },
    {
     "expr": "sum (\n  avg by (tenant_name, workstation, pod) (\n    rate(application_uno_orchestrator_job_execution_delay_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval])\n  )\n) * 60",
     "legendFormat": "completion rate"
    },
    {
     "expr": "avg by (deployment) (kube_deployment_status_replicas_available{deployment=~\"$Release-orchestrator|$Release-scheduler\", namespace=~\"$Namespace\"})",
     "legendFormat": "replicas of {{deployment}}"
    }
   ]
  },
  {
   "title": "Workstations Available Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(tenant_name, folder, name) (\n  (application_uno_workstation_limit_free_jobs{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\"} >= 0)\n)\n/\navg by(tenant_name, folder, name) (\n  (application_uno_workstation_limit_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\"} >= 0)\n)",
     "legendFormat": "{{tenant_name}} - {{folder}}{{name}}"
    }
   ]
  },
  {
   "title": "Execution delay by workstation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (tenant_name, workstation) (\n  rate(\n    application_uno_orchestrator_job_execution_delay_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"} [$__rate_interval]\n  ) >= 0\n  /\n  rate(\n    application_uno_orchestrator_job_execution_delay_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"} [$__rate_interval]\n  ) >=0\n)",
     "legendFormat": "{{tenant_name}} - {{workstation}}"
    }
   ]
  },
  {
   "title": "Cloud Task Launcher running tasks by pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  avg by (tenant_name, pod) (\n    application_uno_cloud_executor_running_task_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"} >= 0\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Timer execution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (type) (\n  rate(application_uno_timer_task_execution_lag_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\"}[$__rate_interval]) >=0\n)\n/\nsum by (type) (\n  rate(application_uno_timer_task_execution_lag_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\"}[$__rate_interval]) >=0\n)",
     "legendFormat": "Timer lag {{type}}"
    },
    {
     "expr": "sum by (type) (\n  rate(application_uno_timer_task_execution_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\"}[$__rate_interval]) >= 0\n)\n/\nsum by (type) (\n  rate(application_uno_timer_task_execution_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\"}[$__rate_interval]) >= 0\n)",
     "legendFormat": "Timer avg execution time {{type}}"
    },
    {
     "expr": "sum by (type) (\n  avg by (tenant_name, type, pod) (\n    rate(application_uno_timer_task_execution_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\"}[$__rate_interval]) >= 0\n  )\n)",
     "legendFormat": "Number of execution {{type}}"
    }
   ]
  },
  {
   "title": "AI Agents Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Conversation (last month)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Conversations"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Errors"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_tool_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Tool Errors"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Invoke"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_genaicalls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} GenAI Calls"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Tools"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_response_time_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Respnse Time"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_tool_duration_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    / \n    application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Tool Duration"
      }
     ]
    },
    {
     "title": "Tool Execution (last month)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, workflow, service_name) (\n    max by (tenant_name, agent, mode, model, workflow, service_name) (\n      application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, workflow, service_name) (\n    max by (tenant_name, agent, mode, model, workflow, service_name) (\n      application_uno_aiagent_tool_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode, workflow, service_name) (\n    application_uno_aiagent_tool_duration_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Agent Conversation (last 24h)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_conversations_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Conversations"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Errors"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_tool_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Tool Errors"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_invoke_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Invoke"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_genaicalls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} GenAI Calls"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_tool_calls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Tools"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_response_time_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Response Time"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode) (\n    application_uno_aiagent_tool_duration_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\"\n)",
       "legendFormat": "{{composite_key}} Avg Tool Duration"
      }
     ]
    },
    {
     "title": "Tool Execution (last 24h)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, workflow, service_name) (\n    max by (tenant_name, agent, mode, model, workflow, service_name) (\n      application_uno_aiagent_tool_calls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, workflow, service_name) (\n    max by (tenant_name, agent, mode, model, workflow, service_name) (\n      application_uno_aiagent_tool_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  avg by (tenant_name, agent, mode, workflow, service_name) (\n    application_uno_aiagent_tool_duration_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    /\n    application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"workflow\", \"service_name\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AI Agent Cost (Cloud Service)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, model) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_units_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "{{composite_key}} Daily Units"
      },
      {
       "expr": "label_join(\n  sum by (tenant_name, agent, mode, model) (\n    max by (tenant_name, agent, mode, model) (\n      application_uno_aiagent_units_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "{{composite_key}} Monthly Units"
      }
     ]
    },
    {
     "title": "AI Agent Cost (BYOL)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_tokens_in_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_tokens_out_daily_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_cost_daily_dollars{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_tokens_in_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_tokens_out_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n  max by (tenant_name, agent, mode, model) (\n    application_uno_aiagent_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n  ),\n  \"composite_key\", \"-\", \"tenant_name\", \"agent\", \"mode\", \"model\"\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "AI Agent Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "AI Agent / Tool Calls per minute",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tenant_name, agent, mode) (\n  avg by (tenant_name, agent, mode, pod) (\n    irate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n) * 60",
       "legendFormat": "Agent: {{tenant_name}} - {{agent}} - {{mode}}"
      },
      {
       "expr": "sum by (tenant_name, workflow, service_name, agent, mode) (\n  avg by (tenant_name, workflow, service_name, agent, mode, pod) (\n    irate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n) * 60",
       "legendFormat": "Tool: {{tenant_name}} - {{workflow}} - {{service_name}} - {{agent}} - {{mode}}"
      }
     ]
    },
    {
     "title": "AI Agent / Tool Errors",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (tenant_name, agent, mode) (\n  avg by (tenant_name, agent, mode, pod) (\n    irate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\", status=\"ERROR\"}[$__rate_interval]) >= 0\n  )\n) * 60",
       "legendFormat": "Agent: {{tenant_name}} - {{agent}} - {{mode}}"
      },
      {
       "expr": "sum by (tenant_name, workflow, service_name) (\n  avg by (tenant_name, workflow, service_name, agent, mode, pod) (\n    irate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\", status=\"FAILED\"}[$__rate_interval]) >= 0\n  )\n) * 60",
       "legendFormat": "Tool: {{tenant_name}} - {{workflow}} - {{service_name}}"
      }
     ]
    },
    {
     "title": "AI Agent Response time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (tenant_name, agent, mode) (\n  avg by (tenant_name, agent, mode, status, pod) (\n    rate(application_uno_aiagent_invoke_seconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n) / sum by (tenant_name, agent, mode) (\n  avg by (tenant_name, agent, mode, status, pod) (\n    rate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n)",
       "legendFormat": "Agent: {{tenant_name}} - {{agent}} - {{mode}}"
      }
     ]
    },
    {
     "title": "Tool Duration",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (tenant_name, workflow, service_name, agent, mode) (\n  avg by (tenant_name, workflow, service_name, agent, mode, status, pod) (\n    rate(application_uno_aiagent_tool_seconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n) / sum by (tenant_name, workflow, service_name, agent, mode) (\n  avg by (tenant_name, workflow, service_name, agent, mode, status, pod) (\n    rate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n)",
       "legendFormat": "Tool: {{tenant_name}} - {{workflow}} - {{service_name}} - {{agent}} - {{mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UnO License",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumed unique jobs in current month",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 88 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum(\n    avg by (tenant_name) (\n      application_uno_orchestrator_license_job_count_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", period=\"month\", type=\"unique\", pod=~\"$pod\"} > 0\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 88 },
     "targets": [
      {
       "expr": "round(\n  sum by (type) (\n    avg by (tenant_name, type) (\n      application_uno_orchestrator_license_job_count_number{namespace=~\"$Namespace\", release=~\"$Release\", period=\"month\", pod=~\"$pod\"} > 0\n    )\n  )\n)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Jobs to send to license server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum(\n    avg by (tenant_name) (\n      application_uno_orchestrator_license_job_to_send_jobs{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed AI Execution Units in current month",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum(\n    avg by (tenant_name) (\n      application_uno_aiagent_license_units_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", period=\"month\", type=\"total\", pod=~\"$pod\"} > 0\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed AI Execution Units",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 96 },
     "targets": [
      {
       "expr": "round(\n  sum by (type) (\n    avg by (tenant_name, type) (\n      application_uno_aiagent_license_units_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", period=\"month\", pod=~\"$pod\"} > 0\n    )\n  )\n)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "AI Execution Units to send to license server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum(\n    avg by (tenant_name) (\n      application_uno_aiagent_license_units_to_send{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GenAI Units by Agents in last 30 days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum (\n    avg by (tenant_name, agent, mode, model, pod) (\n      application_uno_aiagent_units_monthly_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed GenAI Units (estimated)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 104 },
     "targets": [
      {
       "expr": "round(\n  sum (\n    avg by (tenant_name, agent, mode, model, pod) (\n      application_uno_aiagent_units_monthly_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n    )\n  ) +\n  sum (\n    avg by (tenant_name) (\n      increase(application_uno_genai_proxy_units_number_total{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\"}[30d])\n    )\n  )\n)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "GenAI Units by Console in last 30 days (estimated)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 108 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(\n  sum (\n    avg by (tenant_name) (\n      increase(application_uno_genai_proxy_units_number_total{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\"}[30d])\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GenAI Cost (BYOL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost last 24h",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\n  max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n    application_uno_genai_cost_daily_dollars{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Monthly Scenario Stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 89 },
     "targets": [
      {
       "expr": "label_join(\n  sum by (scenario, platform, model) (\n    max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n      application_uno_genai_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\"\n)",
       "legendFormat": "{{composite_key}} (Cost)"
      },
      {
       "expr": "label_join(\n  sum by (scenario, platform, model) (\n    max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n      application_uno_genai_stats_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\"\n)",
       "legendFormat": "{{composite_key}} (Count)"
      },
      {
       "expr": "label_join(\n  sum by (scenario, platform, model) (\n    max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n      application_uno_genai_tokens_in_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\"\n)",
       "legendFormat": "{{composite_key}} (Count)"
      },
      {
       "expr": "label_join(\n  sum by (scenario, platform, model) (\n    max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n      application_uno_genai_tokens_out_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n    )\n  ),\n  \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\"\n)",
       "legendFormat": "{{composite_key}} (Count)"
      }
     ]
    },
    {
     "title": "Cost last 30 days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\n  max by (agentMode, completionStatus, conversationId, deleted, deploymentId, deploymentName, feedbackType, model, organizationName, platform, scenario) (\n    application_uno_genai_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Message processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of processed messages by topic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (topic) (\n  avg by (messageSubType, messageType, topic, pod) (\n    rate(application_uno_message_process_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing usage by message type",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (topic, messageType, messageSubType) (\n  avg by (topic, messageType, messageSubType, pod) (\n    rate(application_uno_message_process_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n) / 1000",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Rate of processed messages by message",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (topic, messageType, messageSubType) (\n  avg by (topic, messageType, messageSubType, pod) (\n    rate(application_uno_message_process_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n)",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Message topic consumer lag",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum by (topic, service) (\n  avg by (client_id, kafka_version, partition, topic, pod, service) (\n    kafka_consumer_fetch_manager_records_lag{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "{{service}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Average processing time by message type",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum by (topic, messageType, messageSubType) (\n    avg by (topic, messageType, messageSubType, pod) (\n      rate(application_uno_message_process_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n    )\n  )\n  /\n  sum by (topic, messageType, messageSubType) (\n    avg by (topic, messageType, messageSubType, pod) (\n      rate(application_uno_message_process_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n    )\n  )\n) >= 0",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Message processing delay by topic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(\n  sum by (topic) (\n    avg by (topic, pod) (\n      rate(application_uno_message_process_delay_milliseconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n    )\n  )\n  /\n  sum by (topic) (\n    avg by (topic, pod) (\n      rate(application_uno_message_process_delay_milliseconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n    )\n  )\n) > 0",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message processing errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (topic, messageType, messageSubType) (\n  avg by (topic, messageType, messageSubType, pod) (\n    rate(application_uno_message_process_errors_number_total{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n  )\n)",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "avg by (cacheName, pod) (\n  application_uno_cache_lru_current_size_number{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"} > 0\n)",
       "legendFormat": "{{cacheName}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Cache Hitrate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "avg by (cacheName, pod) (\n  application_uno_cache_lru_hitrate_percentage{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"} > 0\n)",
       "legendFormat": "{{cacheName}} - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Consumer Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg by (client_id, kafka_version, pod) (\n    kafka_consumer_request_rate{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Consumer Avg Fetch Latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (pod) (\n  avg by (client_id, kafka_version, pod) (\n    kafka_consumer_fetch_manager_fetch_latency_avg{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Producer Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg by (client_id, kafka_version, pod) (\n    kafka_producer_request_rate{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "UnO PODs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failing Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "avg by (pod) (\n  kube_pod_status_phase{pod=~\"$Release-.*\", namespace=~\"$Namespace\", phase=\"Failed\", pod=~\"$pod\"}\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "POD replicas",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (deployment) (\n  kube_deployment_status_replicas_available{deployment=~\"$Release-.*\", namespace=~\"$Namespace\"}\n)",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Number of Pod restarts",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (\n  kube_pod_container_status_restarts_total{pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{cpu=\"total\", container!=\"\", pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n)",
       "legendFormat": "{{namespace}} - {{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Memory usage vs Limits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace, pod) (\n  container_memory_usage_bytes{container!=\"\", pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}\n)",
       "legendFormat": "used by {{pod}}"
      },
      {
       "expr": "avg by (namespace, pod) (\n  kube_pod_container_resource_limits{resource=\"memory\", container!=\"\", pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}\n)",
       "legendFormat": "limit for {{pod}}"
      }
     ]
    },
    {
     "title": "Pods Memory available vs Limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace, pod, container) (\n  kube_pod_container_resource_limits{resource=\"memory\", container!=\"\", pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}\n) - on(pod, namespace, container) avg by (namespace, pod, container) (\n  container_memory_usage_bytes{container!=\"\", namespace=~\"$Namespace\", pod=~\"$pod\"}\n)",
       "legendFormat": "available for {{pod}} on {{container}} {{namespace}}"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "avg by (namespace, release, pod, container) (\n  jvm_threads_live_threads{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n)",
       "legendFormat": "{{namespace}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Network I/O Pods (+Received / -Sent)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (namespace, pod) (\n  rate(container_network_receive_bytes_total{ pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n)",
       "legendFormat": "{{namespace}} - {{ pod }} - Received"
      },
      {
       "expr": "avg by (namespace, pod) (\n  rate(container_network_transmit_bytes_total{ pod=~\"$Release-.*\", namespace=~\"$Namespace\", pod=~\"$pod\"}[$__rate_interval]) >= 0\n) * -1",
       "legendFormat": "{{namespace}} - {{ pod }} - Sent"
      }
     ]
    },
    {
     "title": "Available POD replicas",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "max by (deployment) (\n  kube_deployment_status_replicas_available{deployment=~\"$Release-.*\", namespace=~\"$Namespace\"}\n)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "max by (statefulset) (\n  kube_statefulset_status_replicas_current{namespace=~\"$Namespace\"}\n)",
       "legendFormat": "{{statefulset}}"
      }
     ]
    },
    {
     "title": "Available PVC Storage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (persistentvolumeclaim) (\n  kubelet_volume_stats_available_bytes{namespace=~\"$Namespace\"}\n)",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Gateway queue on Agent Manager",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "avg by (tenant_name, gw) (\n  avg by (tenant_name, gw, pod) (\n    application_uno_agentmanager_command_queue_count_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"} >= 0\n  )\n)",
       "legendFormat": "{{tenant_name}} - {{gw}}"
      }
     ]
    },
    {
     "title": "Number of connected gateways",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "avg by (tenant_name, pod) (\n  application_uno_agentmanager_gw_connected_number{namespace=~\"$Namespace\", release=~\"$Release\", tenant_name=~\"$tenant_name\", pod=~\"$pod\"}\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quarkus JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory Max Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 461 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace, release, pod, container) (\n  jvm_memory_max_bytes{ namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"$pod\" }\n)",
       "legendFormat": "{{namespace}} - {{pod}} - {{release}}"
      }
     ]
    },
    {
     "title": "JVM Heap Memory Max Bytes - Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg by (namespace, release, pod, container, id) (\n    jvm_memory_max_bytes{area=\"heap\", namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Heap Memory Used %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 481 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg by (pod, container, id) (\n    jvm_memory_used_bytes{namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"$pod\"}\n  )\n) / sum by (pod) (\n  avg by (pod, container, id) (\n    jvm_memory_max_bytes{ namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"$pod\" }\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM GC Overhead %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg by (pod, container) (\n    jvm_gc_overhead{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n  )\n)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "JVM GC Pause Max Seconds",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 498 },
     "targets": [
      {
       "expr": "avg by (pod, container) (\n  jvm_gc_pause_seconds_max{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}