######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019, 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "aipilot.fullName" . }}

{{- if not .Values.certificates.caPairSecretName }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}-aipilot-selfsigned-issuer
  labels:
{{ include "aipilot.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-selfsigned-ca
  labels:
{{ include "aipilot.labels" . | nindent 4 }}
spec:
  isCA: true
  renewBefore: {{  .Values.certificates.renewBefore }} # 15d
  commonName: aipilot
  secretName: {{ include "aipilot.ca.secret.name" . }} 
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  issuerRef:
    name: {{ $fullName }}-aipilot-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end -}}