######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019, 2024. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "aipilot.fullName" . }}
{{ $certIssuer := include "aipilot.cert.issuer" . }}

kind: Issuer
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
{{- else if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1" }}
apiVersion: certmanager.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" }}
apiVersion: cert-manager.io/v1alpha2
{{- else if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1" }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- end }}
metadata:
  name: {{ $certIssuer }}
  labels:
{{ include "aipilot.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "aipilot.ca.secret.name" . | default "{{ $fullName }}-uno-selfsigned-issuer" }} 