{{- if .Values.translation.google.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aipilot-google-credentials
type: Opaque
data:
  google-credentials.json: {{ .Values.translation.google.credentials | quote }}
{{- end -}}